Braim23 added docs
abpio/abp-commercial-docs pull request #171
Opened 2022-02-28 12:40 UTC by braim23

I created a new documentation that falls between Creating a CRUD Page and Accessing Source Code of Modules:

![155943948-5ed3c8bf-3a96-4ec0-a48f-190fb02ba4d5](https://user-images.githubusercontent.com/94292623/155984734-91f713a8-8fe2-49b7-ab5a-afbef6a5a362.png)
 
So I edited the last part (What's Next?) of the previous docs to make it the reader to this doc as the next one. I hope I didn't make any mistakes.

2022-02-28 12:56 UTC, EngincanV requested changes

2022-02-28 12:56 UTC, EngincanV commented on en/abp-suite/generating-entities-from-an-existing-database-table.md
> +![image-20220228120525546](C:\Users\BetterCallHamza\AppData\Roaming\Typora\typora-user-images\image-20220228120525546.png)
Can you upload the image to [images folder](https://github.com/abpio/abp-commercial-docs/tree/dev/en/images) and update the image source? Also please do this for the rest of the images.

2022-02-28 12:58 UTC, braim23 commented on en/abp-suite/generating-entities-from-an-existing-database-table.md
> +![image-20220228120525546](C:\Users\BetterCallHamza\AppData\Roaming\Typora\typora-user-images\image-20220228120525546.png)
Sure thing I'll start now

2022-02-28 14:44 UTC, EngincanV approved these changes

2022-03-02 12:08 UTC, ebicoglu approved these changes

2022-03-02 12:09 UTC, merged