Added a page for polling to the commercial doc
abpio/abp-commercial-docs pull request #195
Opened 2022-05-11 11:13 UTC by malikmasis

For the second option
closes https://github.com/volosoft/volo/issues/10073

2022-05-17 05:53 UTC, ismcagdas requested changes

2022-05-17 05:53 UTC, ismcagdas commented on en/modules/cms-kit/poll.md
> +You can simply place the widget on a page like below:
```suggestion
The poll system provides a poll [widget](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Widgets) for users to vote and show the result. You can place the widget on a page like the below:
```

2022-05-17 06:47 UTC, ismcagdas approved these changes

2022-05-17 06:47 UTC, ismcagdas commented
@braim23 you can review now.

2022-05-19 09:12 UTC, hikalkan requested changes

2022-05-19 09:12 UTC, hikalkan commented on en/modules/cms-kit/index.md
> +* [**Poll**](poll.md) system to create polls on any resource, like a blog post or a page.
Poll can be used in blog posts and pages in future version (currently now available, so should not be documented like that). However, it is only a use case. Polls are mainly independent components can be used anywhere in a website. My suggestion:

Poll system to create quick polls for users.

2022-05-19 09:12 UTC, hikalkan commented on en/modules/cms-kit/poll.md
> +        widgetName = "poll"
A name like `my-poll-1` would be better to understand this is a custom name. Also, mention that you can concurrently have multiple active poll widgets in your application with different widget names.

2022-05-19 09:12 UTC, hikalkan commented on en/modules/cms-kit/poll.md
> +- `WidgetNames`: List of defined widgets in the poll system.
```suggestion
- `WidgetNames`: List of defined widgets in the poll system. `options.AddWidget` method was a shortcut to add a new widget to this list.
```

2022-05-19 09:13 UTC, hikalkan commented
Thanks @malikmasis good document. I made a few small improvement suggestions.

2022-05-23 08:09 UTC, hikalkan approved these changes

2022-05-23 08:21 UTC, merged