Update LeptonX docs
abpio/abp-commercial-docs pull request #250
Opened 2022-09-07 12:58 UTC by m-aliozkaya

**Added features**
- Images of components
- How to override a component in Blazor and Mvc
- How to override layouts in Blazor and Mvc

2022-09-08 06:55 UTC, enisn approved these changes
Awesome job 🎊

2022-09-08 06:57 UTC, enisn requested changes

2022-09-08 06:57 UTC, enisn commented on en/themes/lepton-x/commercial/mvc.md
> +abp add-package Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX --prerelease
`ABP CLI` accepts `--preview` instead of `--prerelease`
```suggestion
abp add-package Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX --preview
```

2022-09-08 07:53 UTC, enisn approved these changes

2022-09-08 11:11 UTC, braim23 approved these changes

2022-09-14 06:32 UTC, ismcagdas approved these changes

2022-09-14 06:32 UTC, merged