Create: Faq document
abpio/abp-commercial-docs pull request #789
Opened 2024-05-24 10:17 UTC by EnesDONER

New feature added to Cms kit pro

2024-05-24 11:14 UTC, ebicoglu requested changes

2024-05-24 11:14 UTC, ebicoglu commented on en/images/cmskit-module-faq-edit-question-page.png
![image](https://github.com/abpio/abp-commercial-docs/assets/9526587/3edef1f5-492c-4e73-ad8a-80c6ac975b24)

2024-05-24 11:14 UTC, ebicoglu commented on en/images/cmskit-module-faq-edit-page.png
why Order field is not numeric on Edit FAQ? In the Edit Question dialog it looks numeric field.
![image](https://github.com/abpio/abp-commercial-docs/assets/9526587/f941ae1d-4185-4d23-8401-56e4734be464)
![image](https://github.com/abpio/abp-commercial-docs/assets/9526587/ffe65f1c-0cbb-4e8a-abc0-8ab51bb70424)

2024-05-24 11:14 UTC, ebicoglu commented on en/modules/cms-kit/faq.md
Always use **FAQ** not **faq** in the documents.
![image](https://github.com/abpio/abp-commercial-docs/assets/9526587/fc8005d8-79c2-4609-beeb-d879ae656d9c)

2024-05-24 11:14 UTC, ebicoglu commented on en/modules/cms-kit/faq.md
![image](https://github.com/abpio/abp-commercial-docs/assets/9526587/c57a3c07-6e6b-42df-aa18-3b2555968e49)

2024-05-24 12:57 UTC, EnesDONER commented on en/images/cmskit-module-faq-edit-page.png
I use the abp input. These buttons appear when you hover over the input. Just like:
![error](https://github.com/abpio/abp-commercial-docs/assets/95379442/71b3f184-ed2f-4dcc-b9b9-72acda9fd2f3)

2024-06-18 11:51 UTC, ebicoglu approved these changes

2024-06-18 11:51 UTC, merged